train:
  dataset_path: LegacySurvey:split=train:root=/mnt/ceph/users/polymathic/external_data/astro/DECALS_Stein_et_al/:extra=""
  batch_size_per_gpu: 64
student:
  arch: vit_large
  patch_size: 12
  block_chunks: 4
  num_register_tokens: 4
optim:
  epochs: 200
  weight_decay: 0.01
  weight_decay_end: 0.1
  base_lr: 2.0e-04
  warmup_epochs: 32
  layerwise_decay: 1.0
crops:
  global_crops_scale:
  - 0.947
  - 0.947
  local_crops_number: 8
  local_crops_scale:
  - 0.474
  - 0.474
  global_crops_size: 144
  local_crops_size: 60
