name: Linux

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/CI.yml'
      - 'astroclip/*'
      - 'setup.py'
      - 'requirements.txt'
  pull_request:
    branches:
      - '*'
    paths:
      - '*'
permissions:
  contents: write
  checks: write
  pull-requests: write
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: "Install dependencies"
        run: |
            python -m pip install .
            python -m pip install torch lightning[extra] # Extra dependency since we don't want to force user to use torch version
      - name: "Check dependencies aren't broken"
        run: python -m pip check
      - name: "Check package can be imported"
        run: python -c "import astroclip"
      - name: "Run tests"
        run: |
          pip install pytest
          python -m pytest -k 'not _local'
