name: Pre-commit
on:
  push:
    branches:
      - '*'
    paths:
      - '*'
  pull_request:
    branches:
      - '*'
    paths:
      - '*'
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip isort
          python -m pip install pre-commit
      - name: Run pre-commit
        run: python -m pre_commit run --all-files
